export const ROUTES = {
  home: "/dashboard",
  snippets: "/snippets",
  snippetNew: "/snippets/new",
  snippet: (id: string) => `/snippets/${id}`,
  snippetEdit: (id: string) => `/snippets/${id}/edit`,
  bookmarks: "/bookmarks",
  bookmarkNew: "/bookmarks/new",
  bookmark: (id: string) => `/bookmarks/${id}`,
  commands: "/commands",
  commandNew: "/commands/new",
  command: (id: string) => `/commands/${id}`,
  prompts: "/prompts",
  promptNew: "/prompts/new",
  prompt: (id: string) => `/prompts/${id}`,
  projects: "/projects",
  project: (id: string) => `/projects/${id}`,
  projectDoc: (projectId: string, docId: string) => `/projects/${projectId}/docs/${docId}`,
  tags: "/tags",
  search: "/search",
  settings: "/settings",
  login: "/login",
  register: "/register",
} as const;
